package com.manager.model;

public enum TreeNodeType {
    ROOT,
    CONNECTIONS_CATEGORY,
    CONNECTION,
    FOLDER_DATABASES,
    FOLDER_TABLES,
    FOLDER_USERS,
    FOLDER_ADMINISTER,
    FOLDER_SYSTEM_INFO,
    DATABASE,
    TABLE,
    PLACEHOLDER,
    ERROR
}
